### ISSUE TITLE
[feature request] All caps headings

### ISSUE THREAD

**Issue by kunzaatko** [Krasjet/pdf.tocgen#12]
First of all, thanks for the project! It is super cool!
I think all-caps would be a great filter for some headings. Lots of books use all-caps for subheadings.

**Comment by kunzaatko** [comment]
@Krasjet I made an attempt, at implementing a full pattern match filter. Details are in the commit message. Can you give me some feedback, whether tell me whether I am going in the right direction?

**Comment by kunzaatko** [comment]
# TODO:
### Filter class:
- [ ] Fix the tail problem with matching against the whole pattern and accepting only the first full match
- [ ] When we arrive at the end without a match, we should filter the previously accepted `spn`s.
### Spec generation:
- [ ] Add a field with a pattern to the `spec.toml` generation in `pdfxmeta`
### Add tests:
- [ ] Test whether this could be used as the other filters as the 'main' filter and not just a 'checker'
### Add documentation:
- [ ] in README.md
- [ ] in --help

**Comment by Krasjet** [comment]
I'll review this some time after next Thursday. Sorry for the delay.

**Comment by kunzaatko** [comment]
Offcourse :+1:. Take your time!
